name: Local K8s Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy-to-kind:
    name: Helm Upgrade on Local Cluster
    runs-on: [self-hosted, local-k8s]
    steps:
      - name: 📥 Checkout Source Code
        uses: actions/checkout@v4

      - name: ⚙️ Setup Kubeconfig
        run: |
          kind export kubeconfig --name k8s-lab --kubeconfig ./kubeconfig

      - name: 🚀 Upgrade Helm Release
        run: |
          helm upgrade --install portfolio-release .\portfolio-chart\ --namespace portfolio-app --create-namespace --set app.message="Successfully deployed AUTOMATICALLY via GitHub Actions CI/CD Pipeline!" --kubeconfig ./kubeconfig

      - name: 🔄 Restart Backend Workload
        run: |
          kubectl rollout restart deployment/backend-deployment -n portfolio-app --kubeconfig ./kubeconfig

      - name: 🔍 Verify Deployment Status
        run: |
          kubectl get pods -n portfolio-app --kubeconfig ./kubeconfig
